version: 2

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: build docker image
          command: docker build --rm=false -t registry.heroku.com/${HEROKU_APP_NAME}/web .
      - run:
          name: setup heroku cli
          command: bash .circleci/setup_heroku.sh
      - run:
          name: heroku maintenance mode on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: push container to registry.heroku.com
          command: |
            docker login --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com
            docker push registry.heroku.com/${HEROKU_APP_NAME}/web
            heroku container:release web --app ${HEROKU_APP_NAME}
      - run:
          name: heroku maintenance mode off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master